

package:
  name: nodejs
  version: 4.2.6

build:
  number: 0

about:
  home: https://nodejs.org
  license: MIT

source:
  
  fn: node-v4.2.6-linux-x64.tar.gz # [linux64]
  url: https://nodejs.org/dist/v4.2.6/node-v4.2.6-linux-x64.tar.gz # [linux64]
  sha256: 656d8bff06cc5e108b83176f81de7e1eb16392ae0958ec4a7bca2a3a309333a1 # [linux64]
  
  fn: node-v4.2.6-linux-x86.tar.gz # [linux64]
  url: https://nodejs.org/dist/v4.2.6/node-v4.2.6-linux-x86.tar.gz # [linux32]
  sha256: a96ce235e67e994aa5adec8255e13d4fbccd9c5b09b5e9554347dac2b1c5c8a1 # [linux32]
  
  fn: node-v4.2.6-darwin-x64.tar.gz # [linux64]
  url: https://nodejs.org/dist/v4.2.6/node-v4.2.6-darwin-x64.tar.gz # [osx]
  sha256: 259ea77784013c1124506e3d90ee6847b2b9d3c066b6626ed62ebb31ed8e6fe3 # [osx]
  

requirements:
  build:
    - python # [win]

test:
  commands:
    - node --version
    - npm --version
    - npm config get prefix -g
    - npm install babel babel-core babel-preset-es2015 casperjs gulp istanbul jupyter-js-services karma less phantomjs